/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KnockrApp {
    }
    interface KnockrFab {
    }
}
declare global {
    interface HTMLKnockrAppElement extends Components.KnockrApp, HTMLStencilElement {
    }
    var HTMLKnockrAppElement: {
        prototype: HTMLKnockrAppElement;
        new (): HTMLKnockrAppElement;
    };
    interface HTMLKnockrFabElement extends Components.KnockrFab, HTMLStencilElement {
    }
    var HTMLKnockrFabElement: {
        prototype: HTMLKnockrFabElement;
        new (): HTMLKnockrFabElement;
    };
    interface HTMLElementTagNameMap {
        "knockr-app": HTMLKnockrAppElement;
        "knockr-fab": HTMLKnockrFabElement;
    }
}
declare namespace LocalJSX {
    interface KnockrApp {
    }
    interface KnockrFab {
    }
    interface IntrinsicElements {
        "knockr-app": KnockrApp;
        "knockr-fab": KnockrFab;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "knockr-app": LocalJSX.KnockrApp & JSXBase.HTMLAttributes<HTMLKnockrAppElement>;
            "knockr-fab": LocalJSX.KnockrFab & JSXBase.HTMLAttributes<HTMLKnockrFabElement>;
        }
    }
}
